---
title: "Practice2"
author: "Shovit Bhari"
date: "`r Sys.Date() `"
output: html_document
---

```{r setup, include=FALSE}
library(tidytext)
library(ggplot2)
library(tidyverse)
library(stringr)
library(R.utils)
library(ngram)
library(dplyr)
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
if(!file.exists("./Data")){
  dir.create("./Data")
}
Url <- "https://d396qusza40orc.cloudfront.net/dsscapstone/dataset/Coursera-SwiftKey.zip"

if(!file.exists("./Data/Coursera-SwiftKey.zip")){
  download.file(Url,destfile="./Data/Coursera-SwiftKey.zip",mode = "wb")
}

if(!file.exists("./Data/final")){
  unzip(zipfile="./Data/Coursera-SwiftKey.zip",exdir="./Data")
}
```

```{r}
setwd("./Data/final/en_US")
size_blogs <- file.info("en_US.blogs.txt")$size/1024^2
size_news <- file.info("en_US.news.txt")$size/1024^2
size_twitter <- file.info("en_US.twitter.txt")$size/1024^2
size_blogs
```

```{r}
setwd("./Data/final/en_US")
twitter<-readLines("en_US.twitter.txt",warn=FALSE,encoding="UTF-8")
blogs<-readLines("en_US.blogs.txt",warn=FALSE,encoding="UTF-8")
news<-readLines("en_US.news.txt",warn=FALSE,encoding="UTF-8")
```

## Line Count
```{r}
nlblogs <- countLines("en_US/en_US.blogs.txt")
nltwitter <- countLines("en_US/en_US.twitter.txt")
nlnews <- countLines("en_US/en_US.news.txt")
```

## Word Count
```{r}
nwblogs  <- wordcount(blogs, sep = " ")
nwtwitter <- wordcount(twitter, sep = " ")
nwnews  <- wordcount(news, sep = " ")
nwblogs
```


## Char Count
```{r}
nctwitter<-sum(nchar(twitter))
ncblogs<-sum(nchar(blogs))
ncnews<-sum(nchar(news))
nctwitter
```

##Data Frame
```{r}
data <- data.frame("File Name" = c("twitter", "blogs", "news"),
           "Num of lines" = c(nltwitter,nlblogs, nlnews),
           "Num of words" = c(nwblogs, nwnews, nwtwitter),
           "Num of character"=c(ncblogs,ncnews,nctwitter),
           "File Size" = c(size_blogs, size_news, size_twitter))

```

```{r}
datat<- data %>%
        unnest_tokens(word, twitter)
```